---
title: "Homework 4"
author: "Jeanette Shekelle"
date: "11/2/2018"
output: html_document
---


### Problem 1: Create a website


https://jshekelle.github.io/



### Problem 2: Create a flexdashboard


Loading libraries

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
nyc_food_inspect = read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz")
```


```{r}
set.seed(1)

nyc_food_inspect_smaller = 
  nyc_food_inspect %>% 
  select(cuisine_description, dba, score, zipcode, boro) %>% 
  sample_n(5000)
```


### Plotly box plot 

```{r}
nyc_food_inspect_smaller%>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
```


### 

```{r}
nyc_food_inspect_smaller %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar")

```

```{r}
scatter_ggplot = 
  instacart_tiny %>%
  ggplot(aes(x = order_hour_of_day, y = order_dow)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
```


